### ISSUE TITLE
系统管理员没有上传作业这个选项

### ISSUE THREAD

**Issue by Raudience** [DangerFickle/Task-Manage-Front#1]
~~ ~~管理员以及系统管理员，不能点击提交详情页的单个下载，也不能点击全部下载~~ ~~
（是我没有好好看说明，sorry）

**Comment by Raudience** [comment]
2.系统管理员没有上传作业这个选项，在我目前使用情况下，这个系统管理员可能是班长，而班长也是需要上传作业的，所以系统管理员也要能够上传作业

**Comment by Raudience** [comment]
3.前端项目请求的后端api地址能否设置成本地localhost访问，因为我都有服务器放后端+前端了，为什么不直接本地连接

**Comment by Raudience** [comment]
4.批次管理不应该叫作业管理吗，这个项目明明叫”拯救学习委员之作业管理系统“

**Comment by DangerFickle** [comment]
> 管理员以及系统管理员，不能点击提交详情页的单个下载，也不能点击全部下载

已经截止的批次才可以下载，而已截止的批次不可以再提交或取消提交，以保证管理员下载的作业是最终的

**Comment by DangerFickle** [comment]
> 2.系统管理员没有上传作业这个选项，在我目前使用情况下，这个系统管理员可能是班长，（反正不一定就是老师）而班长也是需要上传作业的，所以系统管理员也要能够上传作业

我最初的想法是系统管理员不参与作业的提交，它只是全局管理系统的角色，如果系统部署者是班长或其他班委，应该用系统管理员的账号在人员管理中为其创建一个账户并设置其普通管理员的角色（普通管理员就是为了班委设计的）后续会在角色设置项中去掉系统管理员选项，如果其他班委也有修改人员的需求可以共用同一个系统管理员账户。最后你的建议后续会考虑哦

**Comment by DangerFickle** [comment]
> 3.前端项目请求的后端api地址能否设置成本地localhost访问。因为我都有服务器放后端+前端了，为什么不直接本地连接，反而还要把后端映射到公网上前端才能访问

我试过访问本地后端地址，但没成功，你可以修改前端的【.env.production】文件尝试

**Comment by Raudience** [comment]
5.在人员管理页，修改和创建时间这两项无什必要，而能够直接看到系统角色和班级职务这两项，更有作用。
![image](https://github.com/DangerFickle/Task-Manage-Front/assets/52769726/5836761c-3ccb-4e31-91ea-445df20ff3c0)

**Comment by DangerFickle** [comment]
> 作业管理

作业属于某个批次，批次属于某个课程

**Comment by Raudience** [comment]
> > 3.前端项目请求的后端api地址能否设置成本地localhost访问。因为我都有服务器放后端+前端了，为什么不直接本地连接，反而还要把后端映射到公网上前端才能访问
> 
> 我试过访问本地后端地址，但没成功，你可以修改前端的【.env.production】文件尝试

最开始我就是配置的localhost，但是并不能成功访问，浏览器向我使用的电脑的localhost发送请求，而不是我前端所在的服务器

**Comment by DangerFickle** [comment]
> 5.在人员管理页，修改和创建时间这两项无什必要，而能够直接看到系统角色和班级职务这两项，更有作用。 ![image](https://user-images.githubusercontent.com/52769726/239693438-5836761c-3ccb-4e31-91ea-445df20ff3c0.png)

后面改改，写这个系统花了一周时间，雀氏很多地方想得不够周到，感谢你的建议

**Comment by Raudience** [comment]
哈哈，只是一些看法而已，我不是计科的，很多东西只是会下载和安装而已，否则我就应该push 而不是 issues😘

**Comment by DangerFickle** [comment]
> > > 3.前端项目请求的后端api地址能否设置成本地localhost访问。因为我都有服务器放后端+前端了，为什么不直接本地连接，反而还要把后端映射到公网上前端才能访问
> > 
> > 
> > 我试过访问本地后端地址，但没成功，你可以修改前端的【.env.production】文件尝试
> 
> 最开始我就是配置的localhost，但是并不能成功访问，浏览器向我使用的电脑的localhost发送请求，而不是我前端所在的服务器

正常前后端分离项目，应该就是这样部署的，前端请求是从浏览器发出去的，肯定访问localhost不行的这样就不是服务器而是你的本地了

**Comment by Raudience** [comment]
> > > > 3.前端项目请求的后端api地址能否设置成本地localhost访问。因为我都有服务器放后端+前端了，为什么不直接本地连接，反而还要把后端映射到公网上前端才能访问
> > > 
> > > 
> > > 我试过访问本地后端地址，但没成功，你可以修改前端的【.env.production】文件尝试
> > 
> > 
> > 最开始我就是配置的localhost，但是并不能成功访问，浏览器向我使用的电脑的localhost发送请求，而不是我前端所在的服务器
> 
> 正常前后端分离项目，应该就是这样部署的，前端请求是从浏览器发出去的，肯定访问localhost不行的这样就不是服务器而是你的本地了

哦哦

**Comment by Raudience** [comment]
添加用户时，角色这一项可以默认填充普通用户，这样在导入用户的时候更方便
![image](https://github.com/DangerFickle/Task-Manage-Front/assets/52769726/7ddeb639-c9c3-4e8a-9df9-29c1ce3db9b0)
